name: Deploy Marp Slides to GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pdfs-built: ${{ steps.verify.outputs.pdfs-built }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build PDFs
        run: |
          marp slides.md --pdf --output slides-en.pdf --allow-local-files
          marp slides-fr.md --pdf --output slides-fr.pdf --allow-local-files

      - name: Verify PDFs exist
        id: verify
        run: |
          if [ -f slides-en.pdf ] && [ -f slides-fr.pdf ]; then
            echo "pdfs-built=true" >> $GITHUB_OUTPUT
            echo "PDFs built successfully"
          else
            echo "PDFs not built!"
            exit 1
          fi

      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides-pdfs
          path: |
            slides-en.pdf
            slides-fr.pdf

  publish:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directories
        run: mkdir -p public

      # ———————————————————————
      # Generate English HTML (for GitHub Pages)
      # ———————————————————————
      - name: Convert English Markdown to HTML
        run: |
          npm install -g @marp-team/marp-cli
          marp slides.md \
            --html \
            --output public/index.html \
            --allow-local-files \

      - name: List public directory
        run: ls -la public/

      - name: Verify HTML was generated
        run: |
          if [ ! -f public/index.html ]; then
            echo "HTML not generated!"
            exit 1
          fi

      # Upload only HTML site to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    needs: [build, publish]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download PDFs artifact
        uses: actions/download-artifact@v4
        with:
          name: slides-pdfs
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: The Zone Presentation v${{ github.run_number }}
          body: |
            Automated release of The Zone presentation.
            Commit: ${{ github.sha }}
            ## Files
            - `slides-en.pdf`: English version
            - `slides-fr.pdf`: French version
          files: |
            slides-en.pdf
            slides-fr.pdf
